### PR TITLE
[api] Added type definition for the Monaco-base IDE

### PR DESCRIPTION
**Pull request by jimmy-huang**
Creates API type definition that will add to the Intellisense which
allows code completion.

Signed-off-by: Jimmy Huang <jimmy.huang@intel.com>

### CODE REVIEW

**Comment by grgustaf** [comment]
Typo in 'definition' in commit message.

Also did you make up this word 'typings'? :)

**Comment by jimmy-huang** [comment]
@grgustaf I saw this referenced somewhere that they are called "Typings" in typescript and they are usually sitting inside the module's subfolder or a generic directory like ./typings.  See https://stackoverflow.com/questions/41573822/what-are-typings-in-typescript.

**Comment by jimmy-huang** [comment]
@grgustaf @poussa, I created a PR in the ide to see if @siovene can help tackle couple issues I have,

https://github.com/01org/zephyrjs-ide/pull/194

**Comment by jimmy-huang** [comment]
I am closing this until I have find a better solution.

**Pull request closed without merging**
