### PR TITLE
Fix to allow new boards build CLI ashell

### PR DESCRIPTION
**Pull request by brianjjones**
Fix for #1844
Signed-off-by: Brian J Jones <brian.j.jones@intel.com>

### CODE REVIEW

**Comment by brianjjones** [comment]
@jimmy-huang I thought the only reason to have different boards listed was because they required different settings? That is how its been done for all the other files.  The JSON file isn't responsible for preventing the user from building ashell with an unsupported board.  I can break it out into several boards, but they will all have the same setting, ["CONFIG_USB_CDC_ACM=y"] and that seems to add unnecessary clutter.  If we want to give a warning to the user that their board isn't supported for ASHELL we'll need to add that to the Makefile.

**Comment by jimmy-huang** [comment]
I think the issue is that by putting in "all", it will just append this config to the prj.conf, which we don't want, because if later we support Ashell over some other board that has different transport or configurations, this could interfere or stop the board from working complete, so instead, it is better to just only insert this for the boards we have tested and guaranteed that it will work.  For example, currently only 3 boards  that if you are building ashell later for arduino_101", "stm32f4_disco", "olimex_stm32_e407".   We have ran into this kind of problem before where configs are added without knowing why they were added to the prj.conf, and it makes it really hard to developers later to figure out why they were needed at the first place.

**Comment by brianjjones** [comment]
@jimmy-huang ok updated

**Comment by jimmy-huang** [comment]
+1

**Pull request merged**
