### PR TITLE
[qemu] Increase stack size to avoid failure in network tests

### LINKED ISSUE #1711: [tcp] Stack Check Fail in qemu
### Description

When running [test-tcp6-server.js](https://github.com/01org/zephyr.js/blob/master/tests/test-tcp6-server.js), [test-tcp4-server.js](https://github.com/01org/zephyr.js/blob/master/tests/test-tcp4-server.js) and [test-tcp4-server-DHCP.js](https://github.com/01org/zephyr.js/blob/master/tests/test-tcp4-server-DHCP.js) in qemu, `Stack Check Fail` will occur. But not reproduce on A101 and K64F.

### Test Code

[test-tcp6-server.js](https://github.com/01org/zephyr.js/blob/master/tests/test-tcp6-server.js);
[test-tcp4-server.js](https://github.com/01org/zephyr.js/blob/master/tests/test-tcp4-server.js); 
[test-tcp4-server-DHCP.js](https://github.com/01org/zephyr.js/blob/master/tests/test-tcp4-server-DHCP.js);

### Steps to Reproduction

 1. Start net-tools on Linux:
terminal 1: ` ./loop-socat.sh`
terminal 2: `sudo ./loop-slip-tap.sh`
 2. `make JS=tests/test-tcp6-server.js ROM=256 BOARD=qemu_x86 qemu`

### Actual Result

selection_014

### Expected Result

No error occurs
 
### Test Builds

Branch | Commit Id | Target Device | Test Date | Result
---|---|---|---|---
master | 1b970c8 | QEMU | Dec 13, 2017 | Fail

### PR DESCRIPTION
**Pull request by grgustaf**
Fixes #1711

Signed-off-by: Geoff Gustafson <geoff@linux.intel.com>

### CODE REVIEW

**Comment by jimmy-huang** [comment]
you don't need this if you merged my #1768 patch :)

**Comment by grgustaf** [comment]
@jimmy-huang actually I do because you didn't remove QEMU config and it doesn't fix it. Hooray for 1776!

**Comment by jimmy-huang** [comment]
but instead of changing it, you should remove it.

**Comment by jimmy-huang** [comment]
+1

**Pull request merged**
